name = "DPL"
uuid = "58fbcba3-c33b-45ec-8a76-42966b17b604"
authors = ["Jeffrey Chandler"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
